- hosts: all
  tags:
    - run_docker
  vars_files:
    - secrets.yaml
  tasks:
    - name: Run bot docker container
      docker_container:
        name: balaboba
        image: twobrowin/balaboba:1.1
        state: started
        detach: yes
        restart: yes
        recreate: yes
        env:
          TZ: "Europe/Moscow"
          
          BOT_TOKEN: "{{ bot_token }}"
          SHEETS_ACC_JSON: "{{ sheet_acc_json | string }}"

          SHEETS_NAME: "Таблица адвент календаря ночного петушка"

          SHEET_TIMING:    "Время"
          SHEET_GROUPS:    "Группы"
          SHEET_PIVOT:     "Уже разосланные сообщения"
          SHEET_PHRASES:   "Фразы для поиска"
          SHEET_MAIN_TEXT: "Основной текст"
          SHEET_PICTURES:  "Картинки"

          TIMING_UPDATE_TIME: "60"
